/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all 78 tarot cards
         * @description Retrieve the complete Rider-Waite-Smith tarot deck of 78 cards: 22 Major Arcana (numbered 0-21, representing life lessons, spiritual themes, and karmic influences like The Fool, Death, The Tower) plus 56 Minor Arcana (4 suits × 14 cards each for daily situations and practical matters). Filter by arcana type (major for spiritual guidance, minor for everyday concerns), suit (cups for emotions and relationships, wands for creativity and passion, swords for intellect and conflict, pentacles for material wealth and finances), or card number (Ace=1 for new beginnings, 2-10 for progression, Page=11 for messages, Knight=12 for action, Queen=13 for mastery, King=14 for authority). Returns lightweight basic card data - use GET /cards/:id for full upright and reversed interpretations with keywords. Perfect for building tarot reference libraries, card databases, learning applications, or browsing the complete traditional deck used by professional tarot readers worldwide.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by arcana type. Major arcana (0-21) represents life lessons and spiritual themes. Minor arcana (Ace-King in 4 suits) represents daily situations and practical matters. */
                    arcana?: "major" | "minor";
                    /** @description Filter minor arcana by suit. Cups=emotions/relationships, Wands=creativity/passion, Swords=intellect/conflict, Pentacles=material/finances. Only applies to minor arcana cards. */
                    suit?: "cups" | "wands" | "swords" | "pentacles";
                    /** @description Filter by card number (1-14). Ace=1, numbered cards 2-10, Page=11, Knight=12, Queen=13, King=14. Only applies to minor arcana cards. Major arcana have their own numbering (0-21). */
                    number?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of tarot cards with basic information. Use GET /cards/:id for full details. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total: number;
                            cards: components["schemas"]["BasicCard"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get detailed tarot card information
         * @description Retrieve comprehensive details for a specific tarot card from the traditional Rider-Waite-Smith deck including complete upright meanings (card drawn normally) and reversed meanings (inverted/upside down interpretations for nuanced guidance). Each card provides keywords for quick reference, full interpretations (400+ words each for upright and reversed orientations), and guidance across life domains: love and relationships, career and professional growth, finances and material success, health and wellbeing, spirituality and personal development. Major Arcana cards (0-21) reveal deep spiritual lessons and life-changing themes. Minor Arcana cards (Ace through King in Cups, Wands, Swords, Pentacles) address practical daily situations and specific challenges. Use card ID in kebab-case format: Major Arcana like "fool", "magician", "death", "tower", or Minor Arcana like "ace-of-cups", "seven-of-wands", "queen-of-swords", "king-of-pentacles". Essential for detailed tarot study, reading interpretations, divination apps, fortune-telling platforms, spiritual guidance tools, and professional tarot learning applications.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Unique card identifier in kebab-case. Major arcana: "fool", "magician", "death", etc. Minor arcana: "ace-of-cups", "seven-of-wands", "queen-of-swords", "king-of-pentacles", etc. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Card details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
                /** @description Card not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draw random tarot cards with reproducible results
         * @description Draw 1-78 tarot cards from the complete Rider-Waite-Smith deck with seeded reproducibility for consistent personalized readings. Provide an optional seed string (like "user123-2025-12-27" or "readingId") to ensure the same seed always returns identical cards in the exact same order - essential for daily tarot features, personalized user experiences, shareable readings, or reproducible testing. Omit seed for true random draws each time. Control card reversals (upright vs reversed/inverted orientations - reversed cards provide alternative meanings when drawn upside down) and duplicates (traditional deck draws each of 78 cards once, or oracle-style allows repeating same card). Each drawn card includes position number, reversal state (boolean), keywords for quick interpretation, full meaning text (400+ words), authentic Rider-Waite imagery, and card metadata. Perfect for custom spread builders, random card generators, automated tarot reading platforms, daily card features, meditation apps, journaling prompts, divination tools, and any application requiring reproducible or random tarot draws from the industry-standard 78-card deck (22 Major Arcana spiritual lessons + 56 Minor Arcana practical guidance across 4 suits).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Number of cards to draw (1-78). Common values: 1 for daily card, 3 for past-present-future, 5 for relationship spread, 10 for Celtic Cross. Drawing 78 returns the entire shuffled deck.
                         * @example 3
                         */
                        count: number;
                        /**
                         * @description Optional seed for reproducible results. Same seed = same cards in same order. Use format like "userId-date" for daily consistency, or "readingId" for shareable readings. Omit for true randomness.
                         * @example user123-2025-12-27
                         */
                        seed?: string;
                        /**
                         * @description Whether cards can appear reversed (upside down). Reversed cards have different meanings. Set false for upright-only readings. Default: true (50% chance of reversal per card).
                         * @default true
                         * @example true
                         */
                        allowReversals?: boolean;
                        /**
                         * @description Whether same card can be drawn multiple times. Set false for traditional deck behavior (each card drawn only once). Set true for statistical analysis or oracle-style readings. Default: false.
                         * @default false
                         * @example false
                         */
                        allowDuplicates?: boolean;
                    };
                };
            };
            responses: {
                /** @description Drawn cards */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            seed?: string;
                            cards: components["schemas"]["DrawnCard"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get daily tarot card reading
         * @description Receive a single tarot card for daily guidance and reflection. This endpoint uses date-based seeding to ensure the same user gets the same card on the same day - perfect for "Card of the Day" features. Optionally provide a userId for personalized consistency (user123 always gets the same card on Dec 27), or omit for anonymous daily draws. Returns card with keywords, full meaning, and a daily message summary. Great for tarot apps, wellness platforms, morning ritual apps, and journaling tools.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Optional user identifier for personalized daily readings. Same userId + same date = same card every time. Use database user IDs, email hashes, or session tokens. Omit for anonymous daily cards.
                         * @example user123
                         */
                        userId?: string;
                        /**
                         * @description Date for the reading in YYYY-MM-DD format. Defaults to today (UTC). Useful for viewing past daily cards or pre-generating future readings. Must be valid ISO date string.
                         * @example 2025-12-27
                         */
                        date?: string;
                    };
                };
            };
            responses: {
                /** @description Daily card reading */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            date: string;
                            seed: string;
                            card: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                arcana: "major" | "minor";
                                position: number;
                                reversed: boolean;
                                keywords: string[];
                                meaning: string;
                                imageUrl: string;
                            };
                            dailyMessage: string;
                        };
                    };
                };
                /** @description Failed to draw card */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yes-no": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get yes/no answer to your question
         * @description Ask a specific question and receive a yes/no answer based on a single tarot card draw. Upright cards indicate "Yes" with positive energy, reversed cards indicate "No" with caution. Major Arcana cards (The Fool, Death, etc.) give strong definitive answers, while Minor Arcana cards give qualified nuanced answers. Returns the answer, strength level, drawn card details, and a contextual interpretation explaining why. Perfect for decision-making apps, quick guidance tools, fortune-telling chatbots, and interactive tarot experiences. Optionally provide a seed for reproducible answers.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Your specific yes/no question. Be clear and focused. Good: "Should I move to a new city?" Bad: "What should I do about my life?" The more specific the question, the more useful the tarot guidance.
                         * @example Should I accept the job offer?
                         */
                        question?: string;
                        /**
                         * @description Optional seed for reproducible results. Same seed + same question = same answer. Useful for testing, sharing readings, or ensuring consistency. Omit for random draws each time.
                         * @example optional-seed
                         */
                        seed?: string;
                    };
                };
            };
            responses: {
                /** @description Yes/No answer with interpretation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            question?: string;
                            /** @enum {string} */
                            answer: "Yes" | "No" | "Maybe";
                            /** @enum {string} */
                            strength: "Strong" | "Qualified";
                            card: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                arcana: "major" | "minor";
                                reversed: boolean;
                                keywords: string[];
                                imageUrl: string;
                            };
                            interpretation: string;
                        };
                    };
                };
                /** @description Failed to draw card */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spreads/three-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Three-Card Spread: Past, Present, Future
         * @description Perform the classic three-card tarot spread revealing Past (what led to this situation), Present (current energy and circumstances), and Future (likely outcome if current path continues). The most popular beginner-friendly spread, perfect for quick insights, daily guidance, or exploring specific questions. Each position includes a drawn card with reversal state, keywords, full meaning, and position-specific interpretation. Returns a summary connecting all three cards. Ideal for tarot reading apps, decision-making tools, and personal growth platforms. Optionally provide a seed for reproducible readings.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Optional specific question to focus the reading. Examples: "What should I know about my relationship?", "How can I improve my finances?", "What's blocking my creative growth?" Leave empty for general guidance.
                         * @example What do I need to know about my career?
                         */
                        question?: string;
                        /**
                         * @description Optional seed for reproducible results. Same seed = same 3 cards in same positions. Useful for sharing readings, testing, or ensuring users get consistent results. Omit for random draws.
                         * @example optional-seed
                         */
                        seed?: string;
                    };
                };
            };
            responses: {
                /** @description Three-card spread reading */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            spread: string;
                            question?: string;
                            seed?: string;
                            positions: {
                                position: number;
                                name: string;
                                interpretation: string;
                                card: {
                                    id: string;
                                    name: string;
                                    /** @enum {string} */
                                    arcana: "major" | "minor";
                                    reversed: boolean;
                                    keywords: string[];
                                    meaning: string;
                                    imageUrl: string;
                                };
                            }[];
                            summary?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spreads/celtic-cross": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Celtic Cross Spread (10 cards)
         * @description Perform the legendary Celtic Cross spread - the most comprehensive and detailed tarot reading available, used by professional tarot readers worldwide for over a century. This 10-card layout reveals the complete picture of any situation through distinct positions: Present Situation (what is happening now), Challenge (obstacles crossing your path), Distant Past (root causes), Recent Past (recent influences), Best Outcome (potential positive result), Near Future (what is approaching in weeks ahead), Your Approach (your attitude and self-perception), External Influences (environment and other people impact), Hopes and Fears (your desires and anxieties), and Final Outcome (where everything is headed). Perfect for life-changing decisions, complex relationship questions, career transitions, spiritual guidance, and deep self-discovery. Ideal for professional tarot apps, life coaching platforms, spiritual wellness websites, and divination tools requiring authoritative comprehensive readings. Each card position provides layered insight combining traditional tarot wisdom with modern psychological interpretation for actionable guidance.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example What should I know about this situation? */
                        question?: string;
                        /** @example optional-seed */
                        seed?: string;
                    };
                };
            };
            responses: {
                /** @description Celtic Cross spread reading */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            spread: string;
                            question?: string;
                            seed?: string;
                            positions: {
                                position: number;
                                name: string;
                                interpretation: string;
                                card: {
                                    id: string;
                                    name: string;
                                    /** @enum {string} */
                                    arcana: "major" | "minor";
                                    reversed: boolean;
                                    keywords: string[];
                                    meaning: string;
                                    imageUrl: string;
                                };
                            }[];
                            summary?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spreads/love": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Love Spread (5 cards)
         * @description Perform a specialized 5-card relationship tarot spread analyzing romantic connections, emotional dynamics, and partnership potential. This love-focused reading examines five crucial relationship aspects: You (your current emotional state, needs, and what you bring to the relationship), Partner/Other (their emotional perspective, desires, and energy), Relationship Dynamic (the current energy and connection between you both), Challenge (obstacles needing attention, healing, or communication), and Outcome (where this romantic connection is naturally heading). Perfect for dating apps, relationship counseling platforms, matchmaking services, wellness apps, and romantic guidance tools. Provides deep insight into new relationships, existing partnerships, potential connections, breakup recovery, or self-love journeys. Ideal for understanding compatibility, resolving conflicts, strengthening bonds, or deciding whether to pursue or continue a relationship. Each position reveals emotional truths combining traditional tarot relationship wisdom with modern relationship psychology. Use for individual readings or couples readings to gain perspective on romantic situations from singleness to marriage.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example What do I need to know about my relationship? */
                        question?: string;
                        /** @example optional-seed */
                        seed?: string;
                    };
                };
            };
            responses: {
                /** @description Love spread reading */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            spread: string;
                            question?: string;
                            seed?: string;
                            positions: {
                                position: number;
                                name: string;
                                interpretation: string;
                                card: {
                                    id: string;
                                    name: string;
                                    /** @enum {string} */
                                    arcana: "major" | "minor";
                                    reversed: boolean;
                                    keywords: string[];
                                    meaning: string;
                                    imageUrl: string;
                                };
                            }[];
                            summary?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spreads/career": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Career Spread (7 cards)
         * @description Perform a comprehensive 7-card career tarot spread using SWOT analysis framework (Strengths, Weaknesses, Opportunities, Threats) for professional guidance, business decisions, and vocational clarity. This career-focused reading examines seven strategic business aspects: Current Situation (your present professional position and workplace energy), Strengths (your professional assets, talents, and competitive advantages), Weaknesses (areas needing development, skill gaps, or limiting beliefs), Opportunities (potential growth paths, new ventures, or doors opening), Threats (obstacles, competition, or external challenges), Advice (actionable guidance for navigating your career path), and Outcome (where your professional journey is heading if you follow the guidance). Perfect for career coaching platforms, professional development apps, business consulting tools, job search websites, entrepreneurship platforms, and executive coaching services. Use for career transitions, job offers evaluation, promotion decisions, starting a business, workplace conflicts, finding your calling, or strategic career planning. Combines traditional tarot wisdom with modern SWOT business analysis for practical professional insight. Ideal for employees, entrepreneurs, freelancers, career changers, and anyone seeking vocational direction.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example What do I need to know about my career path? */
                        question?: string;
                        /** @example optional-seed */
                        seed?: string;
                    };
                };
            };
            responses: {
                /** @description Career spread reading */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            spread: string;
                            question?: string;
                            seed?: string;
                            positions: {
                                position: number;
                                name: string;
                                interpretation: string;
                                card: {
                                    id: string;
                                    name: string;
                                    /** @enum {string} */
                                    arcana: "major" | "minor";
                                    reversed: boolean;
                                    keywords: string[];
                                    meaning: string;
                                    imageUrl: string;
                                };
                            }[];
                            summary?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spreads/custom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Custom Spread Builder
         * @description Build and perform your own custom tarot spread with personalized positions and interpretations (1-10 cards). This flexible endpoint lets you create unique spread layouts for any purpose - define your own position names, meanings, and card count to match your specific needs or therapeutic framework. Perfect for therapists using tarot in counseling, coaches creating signature spreads, app developers building custom reading features, spiritual practitioners with proprietary methods, or anyone wanting to design specialized layouts beyond traditional spreads. Create spreads for specific themes like chakra readings (7 cards), lunar phases (8 cards), elements (4 cards), goals setting (any count), shadow work, inner child healing, decision matrices, or creative problem-solving. Each position requires a name and interpretation - you define what each card position represents in your reading. The API draws the exact number of cards you specify and maps them to your custom positions. No pre-generated summary provided - you interpret the reading based on your framework. Ideal for innovative tarot apps, therapeutic tools, personal development platforms, spiritual coaching services, or experimental divination methods. Maximum 10 positions to maintain reading clarity and practical interpretation time.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example My Custom Spread */
                        spreadName?: string;
                        /**
                         * @example [
                         *       {
                         *         "name": "Core Issue",
                         *         "interpretation": "What is really going on"
                         *       },
                         *       {
                         *         "name": "Hidden Factor",
                         *         "interpretation": "What you cannot see"
                         *       },
                         *       {
                         *         "name": "Best Action",
                         *         "interpretation": "What to do next"
                         *       }
                         *     ]
                         */
                        positions: {
                            /** @example Core Issue */
                            name: string;
                            /** @example What is really going on */
                            interpretation: string;
                        }[];
                        /** @example Optional question */
                        question?: string;
                        /** @example optional-seed */
                        seed?: string;
                    };
                };
            };
            responses: {
                /** @description Custom spread reading */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            spread: string;
                            question?: string;
                            seed?: string;
                            positions: {
                                position: number;
                                name: string;
                                interpretation: string;
                                card: {
                                    id: string;
                                    name: string;
                                    /** @enum {string} */
                                    arcana: "major" | "minor";
                                    reversed: boolean;
                                    keywords: string[];
                                    meaning: string;
                                    imageUrl: string;
                                };
                            }[];
                            summary?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BasicCard: {
            /** @example fool */
            id: string;
            /** @example The Fool */
            name: string;
            /**
             * @example major
             * @enum {string}
             */
            arcana: "major" | "minor";
            /**
             * @example cups
             * @enum {string}
             */
            suit?: "cups" | "wands" | "swords" | "pentacles";
            /** @example 0 */
            number: number;
            /** @example https://roxyapi.com/img/tarot/major/fool.jpg */
            imageUrl: string;
        };
        Card: {
            /** @example fool */
            id: string;
            /** @example The Fool */
            name: string;
            /**
             * @example major
             * @enum {string}
             */
            arcana: "major" | "minor";
            /**
             * @example cups
             * @enum {string}
             */
            suit?: "cups" | "wands" | "swords" | "pentacles";
            /** @example 0 */
            number: number;
            /**
             * @example {
             *       "upright": [
             *         "beginnings",
             *         "innocence",
             *         "spontaneity"
             *       ],
             *       "reversed": [
             *         "recklessness",
             *         "fearlessness"
             *       ]
             *     }
             */
            keywords: {
                upright: string[];
                reversed: string[];
            };
            upright: {
                keywords: string[];
                description: string;
                love?: string;
                career?: string;
                finances?: string;
                health?: string;
                spirituality?: string;
            };
            reversed: {
                keywords: string[];
                description: string;
                love?: string;
                career?: string;
                finances?: string;
                health?: string;
                spirituality?: string;
            };
            /** @example https://roxyapi.com/img/tarot/major/fool.jpg */
            imageUrl: string;
        };
        DrawnCard: {
            id: string;
            name: string;
            /** @enum {string} */
            arcana: "major" | "minor";
            /** @enum {string} */
            suit?: "cups" | "wands" | "swords" | "pentacles";
            number?: number;
            position: number;
            reversed: boolean;
            keywords: string[];
            meaning: string;
            imageUrl: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
